name = "cogar"
main = "src/worker.js"
compatibility_date = "2024-06-20"
workers_dev = true

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
 tag = "v1"
 new_classes = ["ChatRoom"]

[[kv_namespaces]]
binding = "CHAT_KV"
id = "2af1dbd7b5fd4490ab5f9b86a1129ae1"

[assets]
binding = "ASSETS"
directory = "public"

[vars]
# Rotate this to change fallback anonymous usernames every 72h bucket
USERNAME_SALT = "thisIsaTemporarySALT"
ALLOW_DEV = "false"
